name: Run Quantum Engine Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours

jobs:
  run_engine:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      FMP_API_KEY: ${{ secrets.FMP_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: (Optional) Fix numpy/pandas incompatibility
        run: |
          pip uninstall -y numpy pandas
          pip install numpy==1.24.3 pandas==1.5.3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Quantum Signal Engine
        run: python quantum_signal_engine.py
